### ISSUE TITLE
screenshots-2

### ISSUE THREAD

**Issue by gbaumgart** [gbaumgart/xamiro#3]
Screenshots of the 2.0 branch:

![all](https://cloud.githubusercontent.com/assets/1205100/12046093/e882934c-aeb0-11e5-9cb0-8579ebd21657.png)
![contextmenu](https://cloud.githubusercontent.com/assets/1205100/12046094/e8ae70de-aeb0-11e5-94c7-772ae908ecbd.png)
![edit_preview](https://cloud.githubusercontent.com/assets/1205100/12046095/e8c20018-aeb0-11e5-820f-c01bde66348d.png)
![selection_049](https://cloud.githubusercontent.com/assets/1205100/12046096/e8cc91b8-aeb0-11e5-9f65-6793ec2fe1aa.png)
![shells](https://cloud.githubusercontent.com/assets/1205100/12046098/e8e64568-aeb0-11e5-8f39-6df1beda1c91.png)
![stats](https://cloud.githubusercontent.com/assets/1205100/12046097/e8d7653e-aeb0-11e5-9971-a660a6e6fb30.png)

**Comment by gbaumgart** [comment]
New modifications on the transparent them
![image](https://cloud.githubusercontent.com/assets/1205100/12463145/2dbef938-bfc2-11e5-8edf-c1978804cb49.png)

**Comment by eae710** [comment]
Looks great!

**Comment by gbaumgart** [comment]
@eae710 :  thanks! In a one month or so its going public. So try it yourself again.

**Comment by gbaumgart** [comment]
Support for RPI/Arduino

![image](https://cloud.githubusercontent.com/assets/1205100/12936535/d76678d4-cf9f-11e5-88cd-f26e363191f4.png)

**Comment by gbaumgart** [comment]
latest 2.0.5 release:

![image](https://cloud.githubusercontent.com/assets/1205100/13831032/fa7b8632-ebd0-11e5-83c2-6a817e21c578.png)

**Comment by eae710** [comment]
Excellent, I will try later :D

**Comment by gbaumgart** [comment]
@eae710 : hi, not sure how you found this repo but since you're are here: i merged the latest beta into the master branch. which will be from now on always the latest version (no releases any more per se). I also fixed all pen issues and I think its an acceptable beta now. Please tell me otherwise.

**Comment by eae710** [comment]
hi @gbaumgart , in my search for a perfect file manager, I found the website [xamiro ](http://xamiro.com/) :) thanks for the summary. Regards
