### ISSUE TITLE
No file install.ph in root folder

### ISSUE THREAD

**Issue by eae710** [gbaumgart/xamiro#4]
In "FTP instalation guide" => 3. rename install.ph_ to install.php, this file no exist.
If enter http://localhost/xamiro/ get some errors in console.

![screenshot_1](https://cloud.githubusercontent.com/assets/472642/12105051/b682fa70-b316-11e5-96a6-37b46f56b9f6.png)

**Comment by gbaumgart** [comment]
Can you install via Zip? The downloader script is broken. Anyway, please come back manjana!

**Comment by eae710** [comment]
yes, from Zip, but in homepage link, https://github.com/gbaumgart/xamiro/archive/2.0.zip :) thanks

**Comment by gbaumgart** [comment]
Hi, sorry I can't reproduce this. 
1. what are using: PHP5.3? 
2. Windows or Linux ? 
3. And can you check with Chrome-Dev-Tools the Network requests possible there is somewhere an error in the response tab.

sorry, but no problem to get this fixed for you.

**Comment by eae710** [comment]
Hi hi,

1. I'm using PHP 5.6
2. Windows 10
3. Yes, I found the problem, the extension=php_fileinfo.dll was turned off. I enabled in my php.ini and xamiro is alive :D

Thanks a lot!

**Comment by gbaumgart** [comment]
awesome! windows was not really supported but ok. 

There is a major update this days, i will let you know!

**Comment by eae710** [comment]
Great! I will be waiting.
